GET http://localhost:3000/users
###
POST http://localhost:3000/productos/create
###
GET http://localhost:3000/productos/4
###
GET http://localhost:3000/documentos/curriculum.doc
###
POST http://localhost:3000/documentos/nuevo
Content-Type: application/json

{
    "nombre": "Trabajo fin de carrera",
    "extension": "pdf",
    "autor": "Sandra Cerro",
    "categoria": "trabajos"
}

###
GET http://localhost:3000/documentos/all?pages=5&order=nombre&filter=autor
